#!/bin/sh
set -e
case "$1" in
  remove|purge)
    if [ -x /usr/bin/glib-compile-schemas ]; then glib-compile-schemas /usr/share/glib-2.0/schemas || true; fi
    if [ -x /usr/bin/gtk-update-icon-cache ]; then gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor || true; fi
    if [ -d /run/systemd/system ]; then systemctl daemon-reload || true; fi
    ;;
esac
if [ "$1" = purge ]; then rm -rf /var/lib/clearpower /etc/clearpower; fi
exit 0
